
// 永久皮肤列表
var dataAttr1=[

    {"id":"141002","name":"奥德赛 凯隐"},
    {"id":"236008","name":"西部魔影 卢锡安"},
    {"id":"122015","name":"神王 德莱厄斯"},
    {"id":"86013","name":"神王 盖伦"},
    {"id":"67011","name":"源计划：净化 薇恩"},
    {"id":"103014","name":"星之守护者 阿狸"},
    {"id":"92016","name":"黎明使者 锐雯"},
    {"id":"157009","name":"黑夜使者 亚索"},
    {"id":"51011","name":"未来战士 凯特琳"},
    {"id":"64011","name":"神拳 李青"},
    {"id":"222004","name":"星之守护者 金克丝"},
    {"id":"81009","name":"电玩勇者 伊泽瑞尔"},
    {"id":"22008","name":"源计划：联合"},
    {"id":"11009","name":"源计划：林"},
    {"id":"64004","name":"至高之拳 李青"},
    {"id":"92003","name":"兔女郎 锐雯"},
    {"id":"11011","name":"玉剑传说 无极"},
    {"id":"114022","name":"玉剑传说 无双"},
    {"id":"84009","name":"KDA 阿卡丽"},
    {"id":"145014","name":"KDA 卡莎"},
    {"id":"103015","name":"KDA 阿狸"},
    {"id":"222013","name":"奥德赛 金克丝"},
    {"id":"157010","name":"奥德赛 亚索"},
    {"id":"21015","name":"星之守护者 厄运小姐"},
    {"id":"16007","name":"星之守护者 索拉卡"},
    {"id":"134006","name":"星之守护者 辛德拉"},
    {"id":"55009","name":"源计划：雄心"},
    {"id":"245003","name":"源计划：自由"},
    {"id":"236006","name":"源计划：雷"},
    {"id":"89008","name":"源计划：山"},
    {"id":"238003","name":"源计划：阴"},
    {"id":"114004","name":"源计划：火"},
    {"id":"99006","name":"星之守护者 拉克丝"},
    {"id":"202004","name":"源计划：升华 烬"},
    {"id":"157002","name":"源计划：风 亚索"},
    {"id":"92018","name":"未来战士 锐雯"},
    {"id":"17018","name":"小蜜蜂 提莫"},
    {"id":"59007","name":"死兆星 嘉文四世"},
    {"id":"24013","name":"武神 贾克斯"},
    {"id":"122004","name":"灌篮高手 德莱厄斯"},
    {"id":"103017","name":"永恒之森 阿狸"},
    {"id":"555016","name":"源计划：毁灭 派克"},
    {"id":"222020","name":"源计划：疯狂 金克丝"},
    {"id":"157017","name":"战场BOSS 亚索"},
    {"id":"202005","name":"暗星尊 烬"},
    {"id":"81021","name":"战斗学院 伊泽瑞尔"},
    {"id":"238013","name":"天煞 劫"},
    {"id":"58009","name":"鳄霸 雷克顿"},
    {"id":"12010","name":"哞利斯塔"},
    {"id":"85007","name":"超级英雄 凯南"},
    {"id":"105008","name":"兔尾巴 菲兹"},
    {"id":"5006","name":"秘密特工 赵信"},
    {"id":"429001","name":"腥红之月 卡莉丝塔"},
    {"id":"81007","name":"光执事 伊泽瑞尔"},
    {"id":"236002","name":"夺命前锋 卢锡安"},
    {"id":"126001","name":"全金属狂潮 杰斯"},
    {"id":"104003","name":"黑帮教父 格雷福斯"},
    {"id":"81003","name":"冰川勇者 伊泽瑞尔"},
    {"id":"89011","name":"月蚀骑士 蕾欧娜"},
    {"id":"89010","name":"日蚀骑士 蕾欧娜"},
    {"id":"42008","name":"电玩上校 库奇"},
    {"id":"412005","name":"死兆星 锤石"},
    {"id":"14005","name":"霸天零式 赛恩"},
    {"id":"18010","name":"驯龙炮手 崔丝塔娜"},
    {"id":"117005","name":"泳池派对 璐璐"},
    {"id":"421002","name":"泳池派对 雷克塞"},
    {"id":"119004","name":"泳池派对 德莱文"},
    {"id":"110004","name":"觅心射手 韦鲁斯"},
    {"id":"103004","name":"偶像歌手 阿狸"},
    {"id":"53006","name":"苹果机器人 布里茨"},
    {"id":"28006","name":"KDA 伊芙琳"},
    {"id":"37009","name":"奥德赛 娑娜"},
    {"id":"54016","name":"奥德赛 墨菲特"},
    {"id":"115007","name":"奥德赛 吉格斯"},
    {"id":"254011","name":"源计划：裁决 蔚"},
    {"id":"40007","name":"星之守护者 迦娜 "},
    {"id":"117006","name":"星之守护者 璐璐"},
    {"id":"78007","name":"星之守护者 波比"},
    {"id":"157003","name":"腥红之月 亚索"},
    {"id":"119002","name":"绞肉机刽子手 德莱文"},
    {"id":"63007","name":"苍穹之光 布兰德"},
    {"id":"412006","name":"西部魔影 锤石"},
    {"id":"4011","name":"未来战士 崔斯特"},
    {"id":"63006","name":"战场BOSS 布兰德"},
    {"id":"61007","name":"死兆星 奥莉安娜"},
    {"id":"121004","name":"死兆星 卡兹克"},
    {"id":"5013","name":"屠龙勇士 赵信"},
    {"id":"91005","name":"腥红之月 泰隆"},
    {"id":"202002","name":"腥红之月 烬"},
    {"id":"110006","name":"死兆星 韦鲁斯"},
    {"id":"17008","name":"欧米伽小队 幽灵特工"},
    {"id":"23004","name":"恶魔之刃 泰达米尔"},
    {"id":"202001","name":"西部牛仔 烬"},
    {"id":"63005","name":"灵魂烈焰 布兰德"},
    {"id":"64010","name":"地下拳王 李青"},
    {"id":"39016","name":"源计划：正义 艾瑞莉娅"},
    {"id":"84014","name":"源计划：暗影 阿卡丽"},
    {"id":"19016","name":"源计划：末日 沃里克"},
    {"id":"86014","name":"德玛西亚警官 盖伦"},
    {"id":"236009","name":"德玛西亚警官 卢锡安"},
    {"id":"51019","name":"电玩女神 凯特琳"},
    {"id":"246001","name":"战场BOSS 奇亚娜"},
    {"id":"145017","name":"电玩女神 卡莎"},
    {"id":"126005","name":"战斗学院 杰斯"},
    {"id":"99015","name":"战斗学院 拉克丝"},
    {"id":"104025","name":"战斗教授 格雷福斯"},
    {"id":"55012","name":"战斗学院 卡特琳娜"},
    {"id":"164002","name":"魔女 卡蜜尔"},
    {"id":"127004","name":"魔女 丽桑卓"},
    {"id":"98015","name":"未来战士 慎"},
    {"id":"107008","name":"霸天猎手 雷恩加尔"},
    {"id":"131011","name":"腥红之月 黛安娜"},
    {"id":"4010","name":"腥红之月 崔斯特"},
    {"id":"105009","name":"银河魔装机神 菲兹"},
    {"id":"67006","name":"苍穹之光 薇恩"},
    {"id":"96008","name":"战地机甲 克格'莫"},
    {"id":"62004","name":"地狱行者 孙悟空"},
    {"id":"54006","name":"霸天巨兽 墨菲特"},
    {"id":"51006","name":"铁血狙击手 凯特琳"},
    {"id":"119003","name":"金牌主播 德莱文"},
    {"id":"80006","name":"屠龙勇士 潘森"},
    {"id":"68003","name":"银河魔装机神 兰博"},
    {"id":"157001","name":"西部牛仔 亚索"},
    {"id":"236001","name":"职业杀手 卢锡安"},
    {"id":"238001","name":"冲击之刃 劫"},
    {"id":"266007","name":"腥红之月 亚托克斯"},
    {"id":"15016","name":"腥红之月 希维尔"},
    {"id":"555009","name":"腥红之月 派克"},
    {"id":"21017","name":"睡衣守护者 厄运小姐"},
    {"id":"99014","name":"睡衣守护者 拉克丝"},
    {"id":"6009","name":"西部魔影 厄加特"},
    {"id":"53021","name":"银白枪骑 布里茨"},
    {"id":"53020","name":"暮色枪骑 布里茨"},
    {"id":"150013","name":"银河魔装机神 纳尔"},
    {"id":"1011","name":"银河魔装机神 安妮"},
    {"id":"40008","name":"玉剑传说 风仙子"},
    {"id":"41008","name":"恐惧新星 普朗克"},
    {"id":"62001","name":"三昧真火 孙悟空"},
    {"id":"45008","name":"最终BOSS 维迦"},
    {"id":"121001","name":"霸天异形 卡’兹克"},
    {"id":"17005","name":"兔宝宝 提莫"},
    {"id":"1005","name":"冰霜烈焰 安妮"},
    {"id":"350001","name":"战斗校长 悠米"},
    {"id":"110007","name":"征服者 韦鲁斯"},
    {"id":"267007","name":"海皇姬 娜美"},
    {"id":"24012","name":"光明骑士 贾克斯"},
    {"id":"122008","name":"热血班长 德莱厄斯"},
    {"id":"245002","name":"任性学霸 艾克"},
    {"id":"103006","name":"风纪委员 阿狸"},
    {"id":"4009","name":"逍遥赌侠 崔斯特"},
    {"id":"86010","name":"暴君 盖伦"},
    {"id":"39005","name":"莲花之令 艾瑞莉娅"},
    {"id":"101003","name":"枯萎之壤 泽拉斯"},
    {"id":"17006","name":"约德尔国队长 提莫"},
    {"id":"18006","name":"火箭达人 崔丝塔娜"},
    {"id":"84004","name":"实习护士 阿卡丽"},
    {"id":"11003","name":"天人合一 易"},
    {"id":"4005","name":"西部牛仔 崔斯特"},
    {"id":"84006","name":"银色之牙 阿卡丽"},
    {"id":"64002","name":"防弹武僧 李青"},
    {"id":"59002","name":"屠龙勇士 嘉文四世"},
    {"id":"55004","name":"暗夜猫女 卡特琳娜"},
    {"id":"18012","name":"欧米伽小队 魔鬼伞兵"},
    {"id":"29008","name":"欧米伽小队 毒针狙击手"},
    {"id":"105010","name":"欧米伽小队 鬼影蛙人"},
    {"id":"45009","name":"欧米伽小队 天雷爆破手"},
    {"id":"143004","name":"驯龙女巫 婕拉"},
    {"id":"141001","name":"摄魂猎手 凯隐"},
    {"id":"7004","name":"邪鸦魅影 乐芙兰"},
    {"id":"105004","name":"虚空海灵 菲兹"},
    {"id":"34008","name":"千纸凤凰 艾尼维亚"},
    {"id":"20008","name":"千纸双子 努努和威朗普"},
    {"id":"16008","name":"睡衣守护者 索拉卡"},
    {"id":"117015","name":"睡衣守护者 璐璐"},
    {"id":"76009","name":"银河魔装机神 奈德丽"},
    {"id":"60005","name":"银河魔装机神 伊莉丝"},
    {"id":"83003","name":"苍穹之光 约里克"},
    {"id":"90006","name":"战场BOSS  玛尔扎哈"},
    {"id":"85006","name":"腥红之月 凯南"},
    {"id":"34005","name":"黯晶凤凰 艾尼维亚"},
    {"id":"74006","name":"驯龙学者 黑默丁格"},
    {"id":"36008","name":"泳池派对 蒙多"},
    {"id":"154002","name":"泳池派对 扎克"},
    {"id":"37005","name":"电玩女神 娑娜"},
    {"id":"54005","name":"冰川巨兽 墨菲特"},
    {"id":"11005","name":"铁血剑豪 易"},
    {"id":"57006","name":"喵凯"},
    {"id":"102004","name":"冰霜亚龙 希瓦娜"},
    {"id":"136002","name":"霸天龙神 奥瑞利安 · 索尔"},
    {"id":"131012","name":"黑潮 黛安娜"},
    {"id":"8008","name":"黑潮 弗拉基米尔"},
    {"id":"50004","name":"驯龙大师 斯维因"},
    {"id":"50003","name":"绝代智将 斯维因"},
    {"id":"59003","name":"龙骑统帅 嘉文四世"},
    {"id":"17004","name":"提莫:'约德尔人的一大步'"},
    {"id":"53011","name":"战场BOSS 布里茨"},
    {"id":"75005","name":"炼狱魔犬 内瑟斯"},
    {"id":"110002","name":"苍穹之光 韦鲁斯"},
    {"id":"51005","name":"女警狙击 凯特琳"},
    {"id":"115003","name":"泳池派对 吉格斯"},
    {"id":"53004","name":"陆地王者4WD 布里茨"},
    {"id":"35008","name":"暗星 萨科"},
    {"id":"18024","name":"小恶魔 崔丝塔娜"},
    {"id":"28005","name":"腥红之月 伊芙琳"},
    {"id":"19003","name":"狼外婆 沃里克"},
    {"id":"432006","name":"巴德·吟游诗人"},
    {"id":"126004","name":"杰斯·光明之锤"},
    {"id":"113007","name":"瑟庄妮·逐晓者"},
    {"id":"48005","name":"灭世魔神 特朗德尔"},
    {"id":"111005","name":"灭世魔神 诺提勒斯"},
    {"id":"75010","name":"灭世魔神 内瑟斯"},
    {"id":"120006","name":"灭世魔神 赫卡里姆"},
    {"id":"2006","name":"牛扒狂战 奥拉夫"},
    {"id":"84008","name":"刺身之拳 阿卡丽"},
    {"id":"89009","name":"烧烤女神 蕾欧娜"},
    {"id":"106005","name":"怒熊 沃利贝尔"},
    {"id":"150004","name":"狂狮 纳尔"},
    {"id":"36009","name":"硬汉 蒙多"},
    {"id":"56006","name":"恶咒亡魂 魔腾"},
    {"id":"10008","name":"钢铁审判官 凯尔"},
    {"id":"27008","name":"黑色天灾 辛吉德"},
    {"id":"13009","name":"瑞兹·白须"},
    {"id":"110005","name":"韦鲁斯·迅箭"},
    {"id":"201003","name":"布隆·狮心"},
    {"id":"79009","name":"古拉加斯·碎桶者"},
    {"id":"43005","name":"光明骑士 卡尔玛"},
    {"id":"2005","name":"黑暗骑士 奥拉夫"},
    {"id":"12008","name":"黑暗骑士 阿利斯塔"},
    {"id":"8007","name":"学生会长 弗拉基米尔"},
    {"id":"104006","name":"无情重炮 格雷福斯"},
    {"id":"133003","name":"死亡之鹰 奎因"},
    {"id":"266003","name":"狂鲨 亚托克斯"},
    {"id":"23007","name":"梦魇 泰达米尔"},
    {"id":"81008","name":"黑桃皇牌 伊泽瑞尔"},
    {"id":"35007","name":"万能小丑 萨科"},
    {"id":"82005","name":"梅花国王 莫德凯撒"},
    {"id":"134003","name":"方块王后 辛德拉"},
    {"id":"26005","name":"腥红之月 基兰"},
    {"id":"33007","name":"圣金甲虫 拉莫斯"},
    {"id":"72004","name":"圣金甲虫 斯卡纳"},
    {"id":"15007","name":"光明骑士 希维尔"},
    {"id":"19008","name":"黑暗骑士 沃里克"},
    {"id":"22007","name":"黑暗骑士 艾希"},
    {"id":"111004","name":"光明骑士 诺提勒斯"},
    {"id":"106004","name":"警长 沃利贝尔"},
    {"id":"28004","name":"惊天魔盗 伊芙琳"},
    {"id":"48004","name":"巡逻警官 特朗德尔"},
    {"id":"29006","name":"绝影神偷 图奇"},
    {"id":"254003","name":"铁拳执事 蔚"},
    {"id":"4008","name":"逆转裁判 崔斯特"},
    {"id":"57005","name":"绿茵门神 茂凯"},
    {"id":"112003","name":"造物主 维克托"},
    {"id":"40003","name":"寒冰女皇 迦娜"},
    {"id":"2004","name":"五杀摇滚鼓手 奥拉夫"},
    {"id":"131001","name":"暗黑女武神 黛安娜"},
    {"id":"4006","name":"皇家火枪手 崔斯特"},
    {"id":"1006","name":"安伯斯与提妮"},
    {"id":"122001","name":"铁血帝皇 德莱厄斯"},
    {"id":"24006","name":"少林武僧 贾克斯"},
    {"id":"16002","name":"月光女神阿忒弥斯 索拉卡"},
    {"id":"22005","name":"紫晶射手 艾希"},
    {"id":"5003","name":"绞肉机角斗士 赵信"},
    {"id":"86005","name":"孤高游侠 盖伦"},
    {"id":"1007","name":"科学怪熊的新娘 安妮"},
    {"id":"21006","name":"黑帮狂花 厄运小姐"},
    {"id":"55006","name":"沙漠风暴 卡特琳娜"},
    {"id":"37002","name":"五杀摇滚键盘手 娑娜"},
    {"id":"54004","name":"黑曜石守护者 墨菲特"},
    {"id":"80004","name":"钢铁意志 潘森"},
    {"id":"18003","name":"烈焰雄心 崔丝塔娜"},
    {"id":"38004","name":"先驱行者 卡萨丁"},
    {"id":"53005","name":"戴一个表 布里茨"},
    {"id":"24005","name":"百夫长 贾克斯"},
    {"id":"25003","name":"刀锋女王 莫甘娜"},
    {"id":"19007","name":"荒野豺狼 沃里克"},
    {"id":"14004","name":"战争机器 赛恩"},
    {"id":"105002","name":"苔原猎手 菲兹"},
    {"id":"104001","name":"怒之火炮 格雷福斯"},
    {"id":"91002","name":"血色精锐 泰隆"},
    {"id":"21003","name":"特工狂花 厄运小姐"},
    {"id":"41001","name":"幽灵船长 普朗克"},
    {"id":"7002","name":"社会名流 乐芙兰"},
    {"id":"2003","name":"铁哥们儿 奥拉夫"},
    {"id":"99002","name":"游侠法师 拉克丝"},
    {"id":"23001","name":"勇敢的心 泰达米尔"},
    {"id":"3005","name":"风执事 加里奥"},
    {"id":"12006","name":"地狱火 阿利斯塔"},
    {"id":"20004","name":"合金装备 努努"},
    {"id":"32006","name":"小小骑士 阿木木"},
    {"id":"15001","name":"战场公主 希维尔"},
    {"id":"50001","name":"北领前线 斯维因"},
    {"id":"86003","name":"铁甲雄心 盖伦"},
    {"id":"58003","name":"血色暴君 雷克顿"},
    {"id":"76006","name":"铁血猎手 奈德丽"},
    {"id":"106003","name":"符文战熊 沃利贝尔"},
    {"id":"4003","name":"魔幻卡牌 崔斯特"},
    {"id":"427002","name":"灌篮高手 艾翁"},
    {"id":"201011","name":"黑帮管家 布隆"},
    {"id":"68004","name":"废土男爵 兰博"},
    {"id":"420002","name":"抵抗军炎魔 俄洛伊"},
    {"id":"69008","name":"上古魔蛇 卡西奥佩娅"},
    {"id":"10009","name":"五杀摇滚女声主唱 凯尔"},
    {"id":"23002","name":"国王 泰达米尔"},
    {"id":"99004","name":"星际迷航 拉克丝"},
    {"id":"21002","name":"法国皇室 厄运小姐"},
    {"id":"42003","name":"红色男爵 库奇"},
    {"id":"254002","name":"女警官 蔚"},
    {"id":"36003","name":"律政大亨 蒙多"},
    {"id":"76004","name":"艳后 奈德丽"},
    {"id":"30003","name":"死神 卡尔萨斯"},
    {"id":"15004","name":"钢铁之心 希维尔"},
    {"id":"35006","name":"武动巅峰 萨科"},
    {"id":"122002","name":"生化骑士 德莱厄斯"},
    {"id":"111003","name":"宇航员 诺提勒斯"},
    {"id":"3004","name":"地狱之门卫士 加里奥"},
    {"id":"32007","name":"殇之机器人 阿木木"},
    {"id":"22004","name":"女皇 艾希"},
    {"id":"34001","name":"双重冰晶 艾尼维亚"},
    {"id":"31002","name":"绅士 科'加斯"},
    {"id":"98005","name":"战国大名 慎"},
    {"id":"143002","name":"鬼影森森 婕拉"},
    {"id":"16003","name":"圣洁化身 索拉卡"},
    {"id":"10003","name":"大天使长米迦勒 凯尔"},
    {"id":"110009","name":"地狱火 韦鲁斯"},
    {"id":"45013","name":"永恒之森 维迦"},
    {"id":"56007","name":"永恒之森 魔腾"},
    {"id":"3013","name":"地狱火 加里奥"},
    {"id":"98016","name":"奈落之炎 慎"},
    {"id":"77005","name":"龙神之力 乌迪尔"},
    {"id":"79006","name":"美酒节特使 古拉加斯"},
    {"id":"36006","name":"战争血统 蒙多"},
    {"id":"45006","name":"穿着正装的恶魔 维迦"},
    {"id":"35005","name":"飞越疯人院 萨科"},
    {"id":"78005","name":"军神战甲 波比"},
    {"id":"35002","name":"贵族血统 萨科"}
    
];

// 守卫列表
var dataAttr2=[
    {"id":"136","name":"战斗学院杜朗德尔 守卫"},
    {"id":"134","name":"狗狗 守卫"},
    {"id":"133","name":"猫猫 守卫"},
    {"id":"130","name":"低调雪人 守卫"},
    {"id":"120","name":"睡衣守护者 守卫"},
    {"id":"115","name":"太空蜥蜴 守卫"},
    {"id":"107","name":"未来战士2018守卫"},
    {"id":"91","name":"神剑 守卫"},
    {"id":"77","name":"未来战士 守卫"},
    {"id":"82","name":"腐败者守卫"},
    {"id":"80","name":"神拳 守卫"},
    {"id":"76","name":"魔龙之眼 守卫"},
    {"id":"70","name":"吸血鬼魄罗守卫"},
    {"id":"63","name":"魔法少女守卫"},
    {"id":"62","name":"游戏开始 守卫"},
    {"id":"61","name":"侦查无人机 守卫"},
    {"id":"59","name":"死兆星守卫"},
    {"id":"57","name":"霸天零式守卫"},
    {"id":"56","name":"这货不是眼"},
    {"id":"49","name":"火龙里格守卫"},
    {"id":"44","name":"光学增强器守卫"},
    {"id":"23","name":"金球守卫"},
    {"id":"21","name":"屠龙勇士守卫"},
    {"id":"10","name":"星坠守卫"},
    {"id":"11","name":"德莱文守卫"},
    {"id":"12","name":"光辉守卫"},
    
];


// 炫彩皮肤
var dataAttr3=[
    {"id":"12011","name":"哞利斯塔 草莓味牛奶","num":"12"},
    {"id":"12012","name":"哞利斯塔 青苹果味牛奶","num":"12"},
    {"id":"12013","name":"哞利斯塔 香蕉味牛奶","num":"12"},
    {"id":"12014","name":"哞利斯塔 蓝莓味牛奶","num":"12"},
    {"id":"12015","name":"哞利斯塔 巧克力味牛奶","num":"12"},
    {"id":"12016","name":"哞利斯塔 酸奶","num":"12"},
    {"id":"12017","name":"哞利斯塔 花生味牛奶","num":"12"},
    {"id":"12018","name":"哞利斯塔 葡萄味牛奶","num":"12"},
    {"id":"122009","name":"灌篮高手 德莱厄斯 紫金王朝","num":"122"},
    {"id":"122010","name":"灌篮高手 德莱厄斯 传奇雷鸟","num":"122"},
    {"id":"122011","name":"灌篮高手 德莱厄斯 绿衫战神","num":"122"},
    {"id":"122012","name":"灌篮高手 德莱厄斯 罪城霸业","num":"122"},
    {"id":"122013","name":"灌篮高手 德莱厄斯 逆袭传奇","num":"122"},
    {"id":"238005","name":"冲击之刃 劫 备前上忍","num":"238"},
    {"id":"238008","name":"冲击之刃 劫 甲贺上忍","num":"238"},
    {"id":"238009","name":"冲击之刃 劫 户隐上忍","num":"238"},
    {"id":"245004","name":"时之砂 艾克 秩序","num":"245"},
    {"id":"245005","name":"时之砂 艾克 圣炎","num":"245"},
    {"id":"245006","name":"时之砂 艾克 慈土","num":"245"},
    {"id":"245007","name":"时之砂 艾克 威金","num":"245"},
    {"id":"245008","name":"时之砂 艾克 净流","num":"245"},
    {"id":"245009","name":"时之砂 艾克 永生","num":"245"},
    {"id":"245010","name":"时之砂 艾克 邪龙","num":"245"},
    {"id":"5009","name":"镇东将军 赵云","num":"5"},
    {"id":"5010","name":"虎威将军 赵云","num":"5"},
    {"id":"5011","name":"禁军统帅 赵云","num":"5"},
    {"id":"114006","name":"女校长 菲奥娜 燃烧的教鞭","num":"114"},
    {"id":"114007","name":"女校长 菲奥娜 精准的眼力","num":"114"},
    {"id":"114008","name":"女校长 菲奥娜 经典传承者","num":"114"},
    {"id":"114009","name":"女校长 菲奥娜 差生毁灭者","num":"114"},
    {"id":"114010","name":"女校长 菲奥娜 优雅的风度","num":"114"},
    {"id":"114011","name":"女校长 菲奥娜 高洁的威严","num":"114"},
    {"id":"114012","name":"女校长 菲奥娜 教育的荣光","num":"114"},
    {"id":"114013","name":"女校长 菲奥娜 梦幻的倩影","num":"114"},
    {"id":"119007","name":"金牌主播 德莱文 从不断气闪电嘴","num":"119"},
    {"id":"119008","name":"金牌主播 德莱文 玩梗达人金话筒","num":"119"},
    {"id":"119009","name":"金牌主播 德莱文 瓜皮杀手王牌讲师","num":"119"},
    {"id":"119010","name":"金牌主播 德莱文 理性分析数据帝","num":"119"},
    {"id":"119011","name":"金牌主播 德莱文 神秘力量预言帝","num":"119"},
    {"id":"157007","name":"西部牛仔 亚索 大地惊雷","num":"157"},
    {"id":"157008","name":"西部牛仔 亚索 浴血金沙","num":"157"},
    {"id":"17015","name":"欧米伽小队 幽灵特工 雪境幽灵","num":"17"},
    {"id":"17016","name":"欧米伽小队 幽灵特工 沙漠幽灵","num":"17"},
    {"id":"17017","name":"欧米伽小队 幽灵特工 死沼幽灵","num":"17"},
    {"id":"18013","name":"欧米伽小队 魔鬼伞兵 雪境魔鬼","num":"18"},
    {"id":"18014","name":"欧米伽小队 魔鬼伞兵 山岩魔鬼","num":"18"},
    {"id":"18015","name":"欧米伽小队 魔鬼伞兵 丛林魔鬼","num":"18"},
    {"id":"18016","name":"欧米伽小队 魔鬼伞兵 死沼魔鬼","num":"18"},
    {"id":"18017","name":"欧米伽小队 魔鬼伞兵 碧海魔鬼","num":"18"},
    {"id":"105011","name":"欧米伽小队 鬼影蛙人 雪境鬼影","num":"105"},
    {"id":"105012","name":"欧米伽小队 鬼影蛙人 死沼鬼影","num":"105"},
    {"id":"105013","name":"欧米伽小队 鬼影蛙人 红海鬼影","num":"105"},
    {"id":"29009","name":"欧米伽小队 毒针狙击手 雪境毒针","num":"29"},
    {"id":"29010","name":"欧米伽小队 毒针狙击手 沙漠毒针","num":"29"},
    {"id":"29011","name":"欧米伽小队 毒针狙击手 死沼毒针","num":"29"},
    {"id":"157004","name":"西部牛仔 亚索 赤胆威龙","num":"157"},
    {"id":"157005","name":"西部牛仔 亚索 日落狂沙","num":"157"},
    {"id":"157006","name":"西部牛仔 亚索 原野奇侠","num":"157"},
    {"id":"41009","name":"恐惧新星 普朗克 “燃烧银河号”船长","num":"41"},
    {"id":"41010","name":"恐惧新星 普朗克 “星河维序号”船长","num":"41"},
    {"id":"41011","name":"恐惧新星 普朗克“贪婪黑洞号”船长","num":"41"},
    {"id":"41012","name":"恐惧新星 普朗克“皇家私掠号”船长","num":"41"},
    {"id":"41013","name":"恐惧新星 普朗克“夺命死星号”船长","num":"41"},
    {"id":"45010","name":"欧米伽小队 天雷爆破手 碧海天雷","num":"45"},
    {"id":"45011","name":"欧米伽小队 天雷爆破手 死沼天雷","num":"45"},
    {"id":"45012","name":"欧米伽小队 天雷爆破手 雪境天雷","num":"45"},
    {"id":"57008","name":"喵凯 萌萌粉","num":"57"},
    {"id":"57009","name":"喵凯 喜悦灰","num":"57"},
    {"id":"57010","name":"喵凯 怪怪橙","num":"57"},
    {"id":"57011","name":"喵凯 爽爽蓝","num":"57"},
    {"id":"57012","name":"喵凯 呆呆青","num":"57"},
    {"id":"57013","name":"喵凯 淡定桃","num":"57"},
    {"id":"57014","name":"喵凯 期待绿","num":"57"},
    {"id":"57015","name":"喵凯 悲伤紫","num":"57"},
    {"id":"105005","name":"潮汐海灵 菲兹 黄刚玉之心","num":"105"},
    {"id":"105006","name":"潮汐海灵 菲兹 蓝宝石之心","num":"105"},
    {"id":"105007","name":"潮汐海灵 菲兹 红水晶之心","num":"105"},
    {"id":"11006","name":"铁血剑豪 易 黄金剑豪","num":"11"},
    {"id":"11007","name":"铁血剑豪 易 明镜止水","num":"11"},
    {"id":"11008","name":"铁血剑豪 易 赤影剑豪","num":"11"},
    {"id":"122005","name":"诺克萨斯之手 德莱厄斯 暗金将军","num":"122"},
    {"id":"122006","name":"诺克萨斯之手 德莱厄斯 烈风将军","num":"122"},
    {"id":"122007","name":"诺克萨斯之手 德莱厄斯 铁血将军","num":"122"},
    {"id":"150005","name":"最后一只恐龙 纳尔 睿智蓝宝石龙","num":"150"},
    {"id":"150006","name":"最后一只恐龙 纳尔 浪漫粉晶龙","num":"150"},
    {"id":"150007","name":"最后一只恐龙 纳尔 好运猫眼石龙","num":"150"},
    {"id":"150008","name":"最后一只恐龙 纳尔 吉祥珍珠龙","num":"150"},
    {"id":"150009","name":"最后一只恐龙 纳尔 神秘星钻龙","num":"150"},
    {"id":"150010","name":"最后一只恐龙 纳尔 驱邪橄榄石龙","num":"150"},
    {"id":"150011","name":"最后一只恐龙 纳尔 福佑海蓝宝石龙","num":"150"},
    {"id":"150012","name":"最后一只恐龙 纳尔 和谐紫水晶龙","num":"150"},
    {"id":"154003","name":"生化魔人 扎克 桔子果冻魔人","num":"154"},
    {"id":"154004","name":"生化魔人 扎克 草莓软糖魔人","num":"154"},
    {"id":"154005","name":"生化魔人 扎克 木瓜泡泡糖魔人","num":"154"},
    {"id":"17012","name":"抹茶味糖果 兔宝宝 提莫","num":"17"},
    {"id":"17013","name":"葡萄味糖果 兔宝宝 提莫","num":"17"},
    {"id":"17009","name":"蓝莓味糖果 兔宝宝 提莫","num":"17"},
    {"id":"17010","name":"草莓味糖果 兔宝宝 提莫","num":"17"},
    {"id":"17011","name":"牛奶味糖果 兔宝宝 提莫","num":"17"},
    {"id":"18007","name":"火箭达人 崔丝塔娜 硬核朋克","num":"18"},
    {"id":"18008","name":"火箭达人 崔丝塔娜 斯卡朋克","num":"18"},
    {"id":"18009","name":"火箭达人 崔丝塔娜 流行朋克","num":"18"},
    {"id":"2007","name":"铁哥们儿 奥拉夫 成吨的伤害","num":"2"},
    {"id":"2008","name":"铁哥们儿 奥拉夫 极限猛男","num":"2"},
    {"id":"2009","name":"铁哥们儿 奥拉夫 粉红铁汉","num":"2"},
    {"id":"2010","name":"铁哥们儿 奥拉夫 暴走怪杰","num":"2"},
    {"id":"2011","name":"铁哥们儿 奥拉夫 断浪之斧","num":"2"},
    {"id":"2012","name":"铁哥们儿 奥拉夫 迷彩战神","num":"2"},
    {"id":"2013","name":"铁哥们儿 奥拉夫 健身教练","num":"2"},
    {"id":"2014","name":"铁哥们儿 奥拉夫 黑拳裁判","num":"2"},
    {"id":"201004","name":"屠龙勇士 布隆 晶龙之威仪","num":"201"},
    {"id":"201005","name":"屠龙勇士 布隆 黑龙之狡黠","num":"201"},
    {"id":"201006","name":"屠龙勇士 布隆 金龙之优雅","num":"201"},
    {"id":"201007","name":"屠龙勇士 布隆 绿龙之无畏","num":"201"},
    {"id":"201008","name":"屠龙勇士 布隆 铜龙之睿智","num":"201"},
    {"id":"201009","name":"屠龙勇士 布隆 银龙之庄严","num":"201"},
    
];

// 头像列表
var dataAttr4=[
    {"id":"4162","name":"死兆星 萨科 图标"},
    {"id":"4030","name":"舔狗图标"},
    {"id":"4025","name":"库奇 柯基图标"},
    {"id":"4026","name":"菲兹 西班牙猎犬图标"},
    {"id":"4021","name":"雷恩猫猫图标"},
    {"id":"4020","name":"约里猫猫图标"},
    {"id":"4019","name":"千纸雪人 威朗普 图标"},
    {"id":"4018","name":"千纸娃娃 努努 图标"},
    {"id":"4017","name":"千纸凤凰 艾尼维亚 图标"},
    {"id":"3891","name":"腥红之月 希维尔 图标"},
    {"id":"3890","name":"腥红之月 亚托克斯 图标"},
    {"id":"3889","name":"腥红之月 派克 图标"},
    {"id":"3842","name":"月蚀图标"},
    {"id":"3841","name":"日蚀图标"},
    {"id":"3840","name":"睡衣守护者 拉克丝"},
    {"id":"3839","name":"睡衣守护者 璐璐"},
    {"id":"3838","name":"睡衣守护者 伊泽瑞尔"},
    {"id":"3837","name":"睡衣守护者 厄运小姐"},
    {"id":"3836","name":"睡衣守护者 索拉卡 "},
    {"id":"3795","name":"K/DA 阿狸 图标"},
    {"id":"3796","name":"K/DA 伊芙琳 图标"},
    {"id":"3798","name":"K/DA 阿卡丽 图标"},
    {"id":"3797","name":"K/DA 卡莎 图标"},
    {"id":"3785","name":"地狱火 阿木木 图标"},
    {"id":"3787","name":"毕达哥拉斯 图标"},
    {"id":"3788","name":"咬咬 图标"},
    {"id":"3789","name":"初级喷火龙 图标"},
    {"id":"3598","name":"西部魔影 厄运金属 图标"},
    {"id":"3592","name":"黑帮管家 魄罗"},
    {"id":"3593","name":"霸天龙神 奥瑞利安 · 索尔 图标"},
    {"id":"3535","name":"傲狮战旗 图标"},
    {"id":"3536","name":"狂狼战旗 图标"},
    {"id":"3494","name":"黑潮 弗拉基米尔图标"},
    {"id":"3495","name":"黑潮 黛安娜图标"},
    {"id":"1392","name":"召唤仪式锅图标"},
    {"id":"1393","name":"大眼巫师帽图标"},
    {"id":"1383","name":"辉煌法杖图标"},
    {"id":"1384","name":"光明之锤图标"},
    {"id":"1385","name":"皮克斯图标"},
    {"id":"1386","name":"和风图标"},
    {"id":"1387","name":"小白图标"},
    {"id":"1388","name":"小黑图标"},
    {"id":"1295","name":"电玩上校 库奇"},
    {"id":"1297","name":"电玩勇者 伊泽瑞尔"},
    {"id":"1211","name":"湮灭图标"},
    {"id":"1115","name":"绝对不是一个维克兹"},
    {"id":"1116","name":"海牛大大"},
    {"id":"938","name":"恶之狼灵"},
    {"id":"939","name":"善之羊灵"},
    {"id":"770","name":"金龙送喜"},
    {"id":"683","name":"女巫的甜点"},
    
];

// 表情列表
var dataAttr5=[
    {"id":"3276","name":"喵","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Sly_Kitty_Inventory.png"},
    {"id":"3275","name":"呵呵-年轻人","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Khazix_Happy_Inventory.png"},
    {"id":"3274","name":"惊","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_CAMILLE_Inventory.png"},
    {"id":"3273","name":"是我","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Yuumi_Happy_Inventory.png"},
    {"id":"3272","name":"不喜欢","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Yuumi_Angry_Inventory.png"},
    {"id":"3271","name":"面什么包？","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Yuumi_Toast_Inventory.png"},
    {"id":"3270","name":"没下次了","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Yuumi_Nervous_Inventory.png"},
    {"id":"3247","name":"嗨起来了","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Annie_Steamed_Inventory.png"},
    {"id":"3246","name":"摸我","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Evelynn_Ooh_Inventory.png"},
    {"id":"3240","name":"都在计划中","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Sylas_AccordingToPlan_TEXT_Inventory.png"},
    {"id":"3239","name":"弱爆","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Sylas_Disapproval_TEXT_Inventory.png"},
    {"id":"3238","name":"你在逗我？","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Sylas_Angry_TEXT_Inventory.png"},
    {"id":"3232","name":"金币涨了","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_LunarRevel_Bristle_Oink_TEXT_Inventory.png"},
    {"id":"3231","name":"嗝~","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_LunarRevel_TahmKench_Blep__TEXT_Inventory.png"},
    {"id":"3230","name":"又拿下一个","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_LunarRevel_Vayne_Cheeky_TEXT_Inventory.png"},
    {"id":"3216","name":"打得不错！","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Neeko_Funny_Inventory_CN_Inventory.png"},
    {"id":"3215","name":"你瞅啥？","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Neeko_CN_Angry_Inventory.png"},
    {"id":"3213","name":"亮瞎！","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Neeko_CN_Rainbow_Inventory.png"},
    {"id":"3192","name":"哔","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Odyssey_Pet_Inventory.png"},
    {"id":"3191","name":"噢!","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Odyssey_Yasuo_Inventory.png"},
    {"id":"3189","name":"惊喜","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Malphite_Odyssey_Inventory.png"},
    {"id":"3188","name":"真酷炫","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Jinx_Crush_Inventory.png"},
    {"id":"3187","name":"这波可以！","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Jinx_NailedIt_Text_Inventory.png"},
    {"id":"3186","name":"笑哭我了","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Jinx_Joy_Text_Inventory.png"},
    {"id":"3185","name":"怪我咯？","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Jinx_Bored_Text_Inventory.png"},
    {"id":"3184","name":"天哪","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Nunu_Snowball_Inventory.png"},
    {"id":"3183","name":"糟了","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Nunu_Shocked_Inventory.png"},
    {"id":"3182","name":"艰难时刻","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Nunu_Confused_Inventory.png"},
    {"id":"3181","name":"上来","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Thresh_Frustrated_Inventory.png"},
    {"id":"3180","name":"突突","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Urgot_Angry_Inventory.png"},
    {"id":"3179","name":"呦吼","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Lucian_Hat_Inventory.png"},
    {"id":"3165","name":"噢不","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Helmet_Bro_Inventory.png"},
    {"id":"3164","name":"如此战争","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Vs_Wolf_Inventory.png"},
    {"id":"3163","name":"拜托？","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Vs_Lion_Inventory.png"},
    {"id":"3152","name":"你看上去很眼熟","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Pyke_Angry_Inventory.png"},
    {"id":"3151","name":"诺提坏坏","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Nautilus_Happy_Inventory.png"},
    {"id":"3150","name":"维他命海","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Gangplank_Trolly_Inventory.png"},
    {"id":"3149","name":"海兽颅骨","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Illaoi_Taunt_Inventory.png"},
    {"id":"3146","name":"研磨处理","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_Graves_DealWithIt_Inventory.png"},
    {"id":"3143","name":"“射”和“啊”","src":"//game.gtimg.cn/images/lol/act/img/emotes/EM_MissFortune_Taunt_Inventory.png"},
    {"id":"3141","name":"也许下次","src":"//game.gtimg.cn/images/lol/act/img/emotes/Fizz_Taunt_Inventory.png"},
    {"id":"1516","name":"告别冷板凳","src":"//game.gtimg.cn/images/lol/act/img/emotes/TahmKench_Grin_Inventory.png"},
    {"id":"1505","name":"企鹅先生","src":"//game.gtimg.cn/images/lol/act/img/emotes/Penguin_Happy_Greetings_Inventory.png"},
    {"id":"1502","name":"哇哦","src":"//game.gtimg.cn/images/lol/act/img/emotes/MCat_Happy_Cute_Inventory.png"},
    {"id":"1501","name":"我生气了！","src":"//game.gtimg.cn/images/lol/act/img/emotes/MCat_Angry_Mad_Inventory.png"},
    {"id":"1499","name":"调皮魄罗","src":"//game.gtimg.cn/images/lol/act/img/emotes/Poro_Happy_Taunt_Inventory.png"},
    {"id":"1498","name":"和平魄罗","src":"//game.gtimg.cn/images/lol/act/img/emotes/Poro_Happy_Cheers_Inventory.png"},
    {"id":"1492","name":"提莫说很好","src":"//game.gtimg.cn/images/lol/act/img/emotes/Teemo_Happy_Cheers_Inventory.png"},
    {"id":"1490","name":"抓狂","src":"//game.gtimg.cn/images/lol/act/img/emotes/Riven_Angry_Battle_Bunny_Mad_Inventory.png"},
    {"id":"1489","name":"不爽","src":"//game.gtimg.cn/images/lol/act/img/emotes/Poppy_Meme_Taunt_Inventory.png"},
    {"id":"1488","name":"来笑一个","src":"//game.gtimg.cn/images/lol/act/img/emotes/Lulu_Happy_Cheerful_Inventory.png"},
    {"id":"1487","name":"你怎能这样","src":"//game.gtimg.cn/images/lol/act/img/emotes/Gnar_Sad_Pout_Inventory.png"},
    {"id":"1481","name":"成功爆炸","src":"//game.gtimg.cn/images/lol/act/img/emotes/Ziggs_Happy_Cheers_Inventory.png"},
    {"id":"1478","name":"向你致敬","src":"//game.gtimg.cn/images/lol/act/img/emotes/Velkoz_Happy_Greetings_Inventory.png"},
    {"id":"1476","name":"就是这么自信","src":"//game.gtimg.cn/images/lol/act/img/emotes/Taric_Love_Glamorus_Inventory.png"},
    {"id":"1474","name":"来搞事吧","src":"//game.gtimg.cn/images/lol/act/img/emotes/LeeSin_Happy_Cheers_Inventory.png"},
    {"id":"1473","name":"有本事来抓我呀！","src":"//game.gtimg.cn/images/lol/act/img/emotes/Jinx_Meme_Taunt_Inventory.png"},
    {"id":"1469","name":"布隆の爱","src":"//game.gtimg.cn/images/lol/act/img/emotes/Braum_Happy_Heart_Inventory.png"},
    {"id":"1468","name":"无法求解","src":"//game.gtimg.cn/images/lol/act/img/emotes/Blitzcrank_Sad_Confused_Inventory.png"},
    {"id":"1467","name":"呜呜呜---","src":"//game.gtimg.cn/images/lol/act/img/emotes/Amumu_Sad_Crying_Inventory.png"},
    {"id":"1464","name":"搞掂！","src":"//game.gtimg.cn/images/lol/act/img/emotes/Fiora_Happy_Cheers_Inventory.png"},
    {"id":"1462","name":"一切尽在掌握","src":"//game.gtimg.cn/images/lol/act/img/emotes/Vayne_Happy_Taunt_Inventory.png"},
    {"id":"1460","name":"喝杯茶压压惊","src":"//game.gtimg.cn/images/lol/act/img/emotes/Caitlyn_Happy_Greetings_Inventory.png"},
    {"id":"1452","name":"下一个轮到你","src":"//game.gtimg.cn/images/lol/act/img/emotes/Darius_Angry_Smile_Inventory.png"},
    {"id":"1030","name":"棒棒哒","src":"//game.gtimg.cn/images/lol/act/img/emotes/Lux_Happy_Cheerful_Inventory.png"},
    {"id":"998","name":"见到你很高兴","src":"//game.gtimg.cn/images/lol/act/img/emotes/Penguin_Love_Cheerful_Inventory.png"},
    
    ];

//小小英雄
var dataAttr6 =[
    {"name":"石像仔 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Craggle_Tier1.LittleLegends_10_01.png"},
    {"name":"石像仔 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Craggle_Tier2.LittleLegends_10_01.png"},
    {"name":"石像仔 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Craggle_Tier3.LittleLegends_10_01.png"},
    {"name":"极冰 石像仔 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_TrueIce_Tier1.LittleLegends_10_01.png"},
    {"name":"极冰 石像仔 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_TrueIce_Tier2.LittleLegends_10_01.png"},
    {"name":"极冰 石像仔 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_TrueIce_Tier3.LittleLegends_10_01.png"},
    {"name":"沙漠使者 石像仔 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Sandbringer_Tier1.LittleLegends_10_01.png"},
    {"name":"沙漠使者 石像仔 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Sandbringer_Tier2.LittleLegends_10_01.png"},
    {"name":"沙漠使者 石像仔 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Sandbringer_Tier3.LittleLegends_10_01.png"},
    {"name":"黑雾 石像仔 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_BlackMist_Tier1.LittleLegends_10_01.png"},
    {"name":"黑雾 石像仔 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_BlackMist_Tier2.LittleLegends_10_01.png"},
    {"name":"黑雾 石像仔 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_BlackMist_Tier3.LittleLegends_10_01.png"},
    {"name":"军团士兵 石像仔 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Legionnaire_Tier1.LittleLegends_10_01.png"},
    {"name":"军团士兵 石像仔 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Legionnaire_Tier2.LittleLegends_10_01.png"},
    {"name":"军团士兵 石像仔 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Legionnaire_Tier3.LittleLegends_10_01.png"},
    {"name":"海克斯科技 石像仔 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Hextech_Tier1.LittleLegends_10_01.png"},
    {"name":"海克斯科技 石像仔 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Hextech_Tier2.LittleLegends_10_01.png"},
    {"name":"海克斯科技 石像仔 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Gargoyle_Hextech_Tier3.LittleLegends_10_01.png"},
    {"name":"嗡嗡虫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Flutterbug_Tier1.LittleLegends_10_01.png"},
    {"name":"嗡嗡虫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Flutterbug_Tier2.LittleLegends_10_01.png"},
    {"name":"嗡嗡虫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Flutterbug_Tier3.LittleLegends_10_01.png"},
    {"name":"极冰 嗡嗡虫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_TrueIce_Tier1.LittleLegends_10_01.png"},
    {"name":"极冰 嗡嗡虫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_TrueIce_Tier2.LittleLegends_10_01.png"},
    {"name":"极冰 嗡嗡虫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_TrueIce_Tier3.LittleLegends_10_01.png"},
    {"name":"沙漠使者 嗡嗡虫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Sandbringer_Tier1.LittleLegends_10_01.png"},
    {"name":"沙漠使者 嗡嗡虫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Sandbringer_Tier2.LittleLegends_10_01.png"},
    {"name":"沙漠使者 嗡嗡虫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Sandbringer_Tier3.LittleLegends_10_01.png"},
    {"name":"军团士兵 嗡嗡虫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Legionnaire_Tier1.LittleLegends_10_01.png"},
    {"name":"军团士兵 嗡嗡虫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Legionnaire_Tier2.LittleLegends_10_01.png"},
    {"name":"军团士兵 嗡嗡虫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Legionnaire_Tier3.LittleLegends_10_01.png"},
    {"name":"以绪塔尔 嗡嗡虫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Ixtali_Tier1.LittleLegends_10_01.png"},
    {"name":"以绪塔尔 嗡嗡虫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Ixtali_Tier2.LittleLegends_10_01.png"},
    {"name":"以绪塔尔 嗡嗡虫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Ixtali_Tier3.LittleLegends_10_01.png"},
    {"name":"蜂魔 嗡嗡虫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Beevil_Tier1.LittleLegends_10_01.png"},
    {"name":"蜂魔 嗡嗡虫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Beevil_Tier2.LittleLegends_10_01.png"},
    {"name":"蜂魔 嗡嗡虫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Buglet_Beevil_Tier3.LittleLegends_10_01.png"},
    {"name":"发条鸟 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Tocker_Tier1.LittleLegends_10_01.png"},
    {"name":"发条鸟 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Tocker_Tier2.LittleLegends_10_01.png"},
    {"name":"发条鸟 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Tocker_Tier3.LittleLegends_10_01.png"},
    {"name":"禁魔石 发条鸟 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Petricite_Tier1.LittleLegends_10_01.png"},
    {"name":"禁魔石 发条鸟 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Petricite_Tier2.LittleLegends_10_01.png"},
    {"name":"禁魔石 发条鸟 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Petricite_Tier3.LittleLegends_10_01.png"},
    {"name":"炼金科技 发条鸟 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Chemtech_Tier1.LittleLegends_10_01.png"},
    {"name":"炼金科技 发条鸟 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Chemtech_Tier2.LittleLegends_10_01.png"},
    {"name":"炼金科技 发条鸟 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Chemtech_Tier3.LittleLegends_10_01.png"},
    {"name":"黑雾 发条鸟 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_BlackMist_Tier1.LittleLegends_10_01.png"},
    {"name":"黑雾 发条鸟 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_BlackMist_Tier2.LittleLegends_10_01.png"},
    {"name":"黑雾 发条鸟 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_BlackMist_Tier3.LittleLegends_10_01.png"},
    {"name":"军团士兵 发条鸟 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Legionnaire_Tier1.LittleLegends_10_01.png"},
    {"name":"军团士兵 发条鸟 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Legionnaire_Tier2.LittleLegends_10_01.png"},
    {"name":"军团士兵 发条鸟 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_Legionnaire_Tier3.LittleLegends_10_01.png"},
    {"name":"花瓣舞者 发条鸟 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_PetalDancer_Tier1.LittleLegends_10_01.png"},
    {"name":"花瓣舞者 发条鸟 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_PetalDancer_Tier2.LittleLegends_10_01.png"},
    {"name":"花瓣舞者 发条鸟 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_HextechBirb_PetalDancer_Tier3.LittleLegends_10_01.png"},
    {"name":"魔力玛 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Melisma_Tier1.9_22_Little_Legends.png"},
    {"name":"魔力玛 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Melisma_Tier2.9_22_Little_Legends.png"},
    {"name":"魔力玛 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Melisma_Tier3.9_22_Little_Legends.png"},
    {"name":"强力打击 魔力玛 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Hardhitter_Tier1.9_22_Little_Legends.png"},
    {"name":"强力打击 魔力玛 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Hardhitter_Tier2.9_22_Little_Legends.png"},
    {"name":"强力打击 魔力玛 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Hardhitter_Tier3.9_22_Little_Legends.png"},
    {"name":"潮流天后 魔力玛 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Popqueen_Tier1.9_22_Little_Legends.png"},
    {"name":"潮流天后 魔力玛 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Popqueen_Tier2.9_22_Little_Legends.png"},
    {"name":"潮流天后 魔力玛 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Popqueen_Tier3.9_22_Little_Legends.png"},
    {"name":"节奏大师 魔力玛 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Beatmaker_Tier1.9_22_Little_Legends.png"},
    {"name":"节奏大师 魔力玛 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Beatmaker_Tier2.9_22_Little_Legends.png"},
    {"name":"节奏大师 魔力玛 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Beatmaker_Tier3.9_22_Little_Legends.png"},
    {"name":"天纵奇才 魔力玛 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Prodigy_Tier1.9_22_Little_Legends.png"},
    {"name":"天纵奇才 魔力玛 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Prodigy_Tier2.9_22_Little_Legends.png"},
    {"name":"天纵奇才 魔力玛 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_Prodigy_Tier3.9_22_Little_Legends.png"},
    {"name":"暗影节拍 魔力玛 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_ShadowBeat_Tier1.9_22_Little_Legends.png"},
    {"name":"暗影节拍 魔力玛 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_ShadowBeat_Tier2.9_22_Little_Legends.png"},
    {"name":"暗影节拍 魔力玛 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SennaBunny_ShadowBeat_Tier3.9_22_Little_Legends.png"},
    {"name":"琦琦 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Qiqi_Tier1.9_22_Little_Legends.png"},
    {"name":"琦琦 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Qiqi_Tier2.9_22_Little_Legends.png"},
    {"name":"琦琦 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Qiqi_Tier3.9_22_Little_Legends.png"},
    {"name":"强力打击 琦琦 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Hardhitter_Tier1.9_22_Little_Legends.png"},
    {"name":"强力打击 琦琦 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Hardhitter_Tier2.9_22_Little_Legends.png"},
    {"name":"强力打击 琦琦 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Hardhitter_Tier3.9_22_Little_Legends.png"},
    {"name":"独奏家 琦琦 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Soloist_Tier1.9_22_Little_Legends.png"},
    {"name":"独奏家 琦琦 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Soloist_Tier2.9_22_Little_Legends.png"},
    {"name":"独奏家 琦琦 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Soloist_Tier3.9_22_Little_Legends.png"},
    {"name":"节奏大师 琦琦 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Beatmaker_Tier1.9_22_Little_Legends.png"},
    {"name":"节奏大师 琦琦 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Beatmaker_Tier2.9_22_Little_Legends.png"},
    {"name":"节奏大师 琦琦 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Beatmaker_Tier3.9_22_Little_Legends.png"},
    {"name":"天纵奇才 琦琦 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Prodigy_Tier1.9_22_Little_Legends.png"},
    {"name":"天纵奇才 琦琦 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Prodigy_Tier2.9_22_Little_Legends.png"},
    {"name":"天纵奇才 琦琦 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_Prodigy_Tier3.9_22_Little_Legends.png"},
    {"name":"贝斯女皇 琦琦 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_BassQueen_Tier1.9_22_Little_Legends.png"},
    {"name":"贝斯女皇 琦琦 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_BassQueen_Tier2.9_22_Little_Legends.png"},
    {"name":"贝斯女皇 琦琦 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_QiyanaDog_BassQueen_Tier3.9_22_Little_Legends.png"},
    {"name":"奥希雅 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Ossia_Tier1.9_22_Little_Legends.png"},
    {"name":"奥希雅 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Ossia_Tier2.9_22_Little_Legends.png"},
    {"name":"奥希雅 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Ossia_Tier3.9_22_Little_Legends.png"},
    {"name":"独奏家 奥希雅 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Soloist_Tier1.9_22_Little_Legends.png"},
    {"name":"独奏家 奥希雅 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Soloist_Tier2.9_22_Little_Legends.png"},
    {"name":"独奏家 奥希雅 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Soloist_Tier3.9_22_Little_Legends.png"},
    {"name":"潮流天后 奥希雅 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Popqueen_Tier1.9_22_Little_Legends.png"},
    {"name":"潮流天后 奥希雅 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Popqueen_Tier2.9_22_Little_Legends.png"},
    {"name":"潮流天后 奥希雅 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Popqueen_Tier3.9_22_Little_Legends.png"},
    {"name":"节奏大师 奥希雅 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Beatmaker_Tier1.9_22_Little_Legends.png"},
    {"name":"节奏大师 奥希雅 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Beatmaker_Tier2.9_22_Little_Legends.png"},
    {"name":"节奏大师 奥希雅 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Beatmaker_Tier3.9_22_Little_Legends.png"},
    {"name":"天纵奇才 奥希雅 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Prodigy_Tier1.9_22_Little_Legends.png"},
    {"name":"天纵奇才 奥希雅 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Prodigy_Tier2.9_22_Little_Legends.png"},
    {"name":"天纵奇才 奥希雅 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_Prodigy_Tier3.9_22_Little_Legends.png"},
    {"name":"燃爆 奥希雅 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_PumpedUp_Tier1.9_22_Little_Legends.png"},
    {"name":"燃爆 奥希雅 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_PumpedUp_Tier2.9_22_Little_Legends.png"},
    {"name":"燃爆 奥希雅 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AkaliDragon_PumpedUp_Tier3.9_22_Little_Legends.png"},
    {"name":"小志1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Shisa_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"小志2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Shisa_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"小志3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Shisa_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"英勇1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Heroic_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"英勇2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Heroic_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"英勇3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Heroic_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"最幼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Littlest_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"最幼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Littlest_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"最幼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Littlest_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"落日1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Sundrop_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"落日2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Sundrop_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"落日3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Sundrop_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"花火1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Firecracker_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"花火2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Firecracker_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"花火3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Firecracker_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"堕落1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Corrupted_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"堕落2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Corrupted_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"堕落3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGShisa_Corrupted_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"软软1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Fuwa_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"软软2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Fuwa_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"软软3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Fuwa_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"遗愿1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_LastWish_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"遗愿2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_LastWish_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"遗愿3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_LastWish_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"热恋1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Lovestruck_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"热恋2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Lovestruck_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"热恋3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Lovestruck_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"黯然1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Eclipse_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"黯然2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Eclipse_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"黯然3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Eclipse_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"花火1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Firecracker_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"花火2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Firecracker_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"花火3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Firecracker_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"晨星1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Daystar_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"晨星2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Daystar_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"晨星3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGPig_Daystar_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"团子1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Dango_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"团子2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Dango_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"团子3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Dango_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"泡泡糖1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Bubblegum_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"泡泡糖2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Bubblegum_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"泡泡糖3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Bubblegum_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"姜饼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Gingersnap_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"姜饼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Gingersnap_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"姜饼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Gingersnap_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"柠檬糖1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Lemondrop_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"柠檬糖2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Lemondrop_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"柠檬糖3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Lemondrop_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"酸莓1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Limeberry_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"酸莓2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Limeberry_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"酸莓3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_Limeberry_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"甜到爆1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_SugarCrash_Tier1.Little_Legends_Star_Guardian.png"},
    {"name":"甜到爆2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_SugarCrash_Tier2.Little_Legends_Star_Guardian.png"},
    {"name":"甜到爆3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SGCat_SugarCrash_Tier3.Little_Legends_Star_Guardian.png"},
    {"name":"镶月 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Moontipped_Tier1.Little_Legends_9_15.png"},
    {"name":"镶月 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Moontipped_Tier2.Little_Legends_9_15.png"},
    {"name":"镶月 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Moontipped_Tier3.Little_Legends_9_15.png"},
    {"name":"林仙 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Fae_Tier1.Little_Legends_9_15.png"},
    {"name":"林仙 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Fae_Tier2.Little_Legends_9_15.png"},
    {"name":"林仙 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Fae_Tier3.Little_Legends_9_15.png"},
    {"name":"蝶耳 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Monarch_Tier1.Little_Legends_9_15.png"},
    {"name":"蝶耳 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Monarch_Tier2.Little_Legends_9_15.png"},
    {"name":"蝶耳 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Monarch_Tier3.Little_Legends_9_15.png"},
    {"name":"雾莓 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Mistberry_Tier1.Little_Legends_9_15.png"},
    {"name":"雾莓 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Mistberry_Tier2.Little_Legends_9_15.png"},
    {"name":"雾莓 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Mistberry_Tier3.Little_Legends_9_15.png"},
    {"name":"不驯 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Untamed_Tier1.Little_Legends_9_15.png"},
    {"name":"不驯 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Untamed_Tier2.Little_Legends_9_15.png"},
    {"name":"不驯 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Untamed_Tier3.Little_Legends_9_15.png"},
    {"name":"永恒 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Eternal_Tier1.Little_Legends_9_15.png"},
    {"name":"永恒 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Eternal_Tier2.Little_Legends_9_15.png"},
    {"name":"永恒 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_Eternal_Tier3.Little_Legends_9_15.png"},
    {"name":"翡翠 桨翼 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Jade_Tier1.Little_Legends_9_15.png"},
    {"name":"翡翠 桨翼 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Jade_Tier2.Little_Legends_9_15.png"},
    {"name":"翡翠 桨翼 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Jade_Tier3.Little_Legends_9_15.png"},
    {"name":"幻魅 桨翼 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Glamorous_Tier1.Little_Legends_9_15.png"},
    {"name":"幻魅 桨翼 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Glamorous_Tier2.Little_Legends_9_15.png"},
    {"name":"幻魅 桨翼 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Glamorous_Tier3.Little_Legends_9_15.png"},
    {"name":"火山口 桨翼 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Caldera_Tier1.Little_Legends_9_15.png"},
    {"name":"火山口 桨翼 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Caldera_Tier2.Little_Legends_9_15.png"},
    {"name":"火山口 桨翼 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Caldera_Tier3.Little_Legends_9_15.png"},
    {"name":"潮池 桨翼 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Tidepool_Tier1.Little_Legends_9_15.png"},
    {"name":"潮池 桨翼 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Tidepool_Tier2.Little_Legends_9_15.png"},
    {"name":"潮池 桨翼 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Tidepool_Tier3.Little_Legends_9_15.png"},
    {"name":"玫瑰蓓蕾 桨翼 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Rosebloom_Tier1.Little_Legends_9_15.png"},
    {"name":"玫瑰蓓蕾 桨翼 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Rosebloom_Tier2.Little_Legends_9_15.png"},
    {"name":"玫瑰蓓蕾 桨翼 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Rosebloom_Tier3.Little_Legends_9_15.png"},
    {"name":"圣诞时节 桨翼 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Yuletide_Tier1.Little_Legends_9_15.png"},
    {"name":"圣诞时节 桨翼 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Yuletide_Tier2.Little_Legends_9_15.png"},
    {"name":"圣诞时节 桨翼 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Turtle_Yuletide_Tier3.Little_Legends_9_15.png"},
    {"name":"珠光 喵卫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Jeweled_Tier1.Little_Legends_9_15.png"},
    {"name":"珠光 喵卫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Jeweled_Tier2.Little_Legends_9_15.png"},
    {"name":"珠光 喵卫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Jeweled_Tier3.Little_Legends_9_15.png"},
    {"name":"暴躁 喵卫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Fierce_Tier1.Little_Legends_9_15.png"},
    {"name":"暴躁 喵卫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Fierce_Tier2.Little_Legends_9_15.png"},
    {"name":"暴躁 喵卫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Fierce_Tier3.Little_Legends_9_15.png"},
    {"name":"影钻 喵卫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Shadowgem_Tier1.Little_Legends_9_15.png"},
    {"name":"影钻 喵卫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Shadowgem_Tier2.Little_Legends_9_15.png"},
    {"name":"影钻 喵卫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Shadowgem_Tier3.Little_Legends_9_15.png"},
    {"name":"天钻 喵卫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Skygem_Tier1.Little_Legends_9_15.png"},
    {"name":"天钻 喵卫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Skygem_Tier2.Little_Legends_9_15.png"},
    {"name":"天钻 喵卫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Skygem_Tier3.Little_Legends_9_15.png"},
    {"name":"霸气 喵卫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Reigning_Tier1.Little_Legends_9_15.png"},
    {"name":"霸气 喵卫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Reigning_Tier2.Little_Legends_9_15.png"},
    {"name":"霸气 喵卫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Reigning_Tier3.Little_Legends_9_15.png"},
    {"name":"阳裔 喵卫 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Sunborne_Tier1.Little_Legends_9_15.png"},
    {"name":"阳裔 喵卫 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Sunborne_Tier2.Little_Legends_9_15.png"},
    {"name":"阳裔 喵卫 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GemTiger_Sunborne_Tier3.Little_Legends_9_15.png"},
    {"name":"企鹅 羽饰骑士1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Classic_Tier1.Companions.png"},
    {"name":"企鹅 羽饰骑士2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Classic_Tier2.Companions.png"},
    {"name":"企鹅 羽饰骑士3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Classic_Tier3.Companions.png"},
    {"name":"鸦领主 羽饰骑士1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Dark_Tier1.Companions.png"},
    {"name":"鸦领主 羽饰骑士2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Dark_Tier2.Companions.png"},
    {"name":"鸦领主 羽饰骑士3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Dark_Tier3.Companions.png"},
    {"name":"极冰 羽饰骑士1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Ice_Tier1.Companions.png"},
    {"name":"极冰 羽饰骑士2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Ice_Tier2.Companions.png"},
    {"name":"极冰 羽饰骑士3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Ice_Tier3.Companions.png"},
    {"name":"特辣 羽饰骑士1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Rooster_Tier1.Companions.png"},
    {"name":"特辣 羽饰骑士2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Rooster_Tier2.Companions.png"},
    {"name":"特辣 羽饰骑士3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Rooster_Tier3.Companions.png"},
    {"name":"幼雏 羽饰骑士1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Yellow_Tier1.Companions.png"},
    {"name":"幼雏 羽饰骑士2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Yellow_Tier2.Companions.png"},
    {"name":"幼雏 羽饰骑士3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Yellow_Tier3.Companions.png"},
    {"name":"樱花 羽饰骑士1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Owl_Tier1.Companions.png"},
    {"name":"樱花 羽饰骑士2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Owl_Tier2.Companions.png"},
    {"name":"樱花 羽饰骑士3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_Owl_Tier3.Companions.png"},
    {"name":"哨兵 符灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Grey_Tier1.Companions.png"},
    {"name":"哨兵 符灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Grey_Tier2.Companions.png"},
    {"name":"哨兵 符灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Grey_Tier3.Companions.png"},
    {"name":"棘背 符灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Lava_Tier1.Companions.png"},
    {"name":"棘背 符灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Lava_Tier2.Companions.png"},
    {"name":"棘背 符灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Lava_Tier3.Companions.png"},
    {"name":"幼苗 符灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Moss_Tier1.Companions.png"},
    {"name":"幼苗 符灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Moss_Tier2.Companions.png"},
    {"name":"幼苗 符灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Moss_Tier3.Companions.png"},
    {"name":"黑雾 符灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Dark_Tier1.Companions.png"},
    {"name":"黑雾 符灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Dark_Tier2.Companions.png"},
    {"name":"黑雾 符灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Dark_Tier3.Companions.png"},
    {"name":"冰川 符灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Ice_Tier1.Companions.png"},
    {"name":"冰川 符灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Ice_Tier2.Companions.png"},
    {"name":"冰川 符灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Ice_Tier3.Companions.png"},
    {"name":"樱花 符灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Spring_Tier1.Companions.png"},
    {"name":"樱花 符灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Spring_Tier2.Companions.png"},
    {"name":"樱花 符灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_MiniGolem_Spring_Tier3.Companions.png"},
    {"name":"软鼻 潜地鼹鼠1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Grey_Tier1.Companions.png"},
    {"name":"软鼻 潜地鼹鼠2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Grey_Tier2.Companions.png"},
    {"name":"软鼻 潜地鼹鼠3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Grey_Tier3.Companions.png"},
    {"name":"烈战 潜地鼹鼠1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Red_Tier1.Companions.png"},
    {"name":"烈战 潜地鼹鼠2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Red_Tier2.Companions.png"},
    {"name":"烈战 潜地鼹鼠3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Red_Tier3.Companions.png"},
    {"name":"空舞 潜地鼹鼠1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Rainbow_Tier1.Companions.png"},
    {"name":"空舞 潜地鼹鼠2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Rainbow_Tier2.Companions.png"},
    {"name":"空舞 潜地鼹鼠3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Rainbow_Tier3.Companions.png"},
    {"name":"淡水 潜地鼹鼠1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Green_Tier1.Companions.png"},
    {"name":"淡水 潜地鼹鼠2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Green_Tier2.Companions.png"},
    {"name":"淡水 潜地鼹鼠3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Green_Tier3.Companions.png"},
    {"name":"笨拙 潜地鼹鼠1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Dark_Tier1.Companions.png"},
    {"name":"笨拙 潜地鼹鼠2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Dark_Tier2.Companions.png"},
    {"name":"笨拙 潜地鼹鼠3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Dark_Tier3.Companions.png"},
    {"name":"剧毒 潜地鼹鼠1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Yellow_Tier1.Companions.png"},
    {"name":"剧毒 潜地鼹鼠2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Yellow_Tier2.Companions.png"},
    {"name":"剧毒 潜地鼹鼠3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Yellow_Tier3.Companions.png"},
    // {"name":"宇航员 鼹鼠 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Astronaut_Tier1.LittleLegends_DarkStar.png"},
    // {"name":"宇航员 鼹鼠 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Astronaut_Tier2.LittleLegends_DarkStar.png"},
    // {"name":"宇航员 鼹鼠 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Miner_Astronaut_Tier3.LittleLegends_DarkStar.png"},
    {"name":"熔皮 怒角1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Red_Tier1.Companions.png"},
    {"name":"熔皮 怒角2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Red_Tier2.Companions.png"},
    {"name":"熔皮 怒角3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Red_Tier3.Companions.png"},
    {"name":"虚空标记 怒角1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Void_Tier1.Companions.png"},
    {"name":"虚空标记 怒角2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Void_Tier2.Companions.png"},
    {"name":"虚空标记 怒角3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Void_Tier3.Companions.png"},
    {"name":"柳皮 怒角1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Green_Tier1.Companions.png"},
    {"name":"柳皮 怒角2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Green_Tier2.Companions.png"},
    {"name":"柳皮 怒角3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Green_Tier3.Companions.png"},
    {"name":"狮心 怒角1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Orange_Tier1.Companions.png"},
    {"name":"狮心 怒角2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Orange_Tier2.Companions.png"},
    {"name":"狮心 怒角3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Orange_Tier3.Companions.png"},
    {"name":"甜筒 怒角1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_IceCream_Tier1.Companions.png"},
    {"name":"甜筒 怒角2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_IceCream_Tier2.Companions.png"},
    {"name":"甜筒 怒角3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_IceCream_Tier3.Companions.png"},
    {"name":"苔原 怒角1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Dark_Tier1.Companions.png"},
    {"name":"苔原 怒角2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Dark_Tier2.Companions.png"},
    {"name":"苔原 怒角3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_Dark_Tier3.Companions.png"},
    // {"name":"胜利怒角","src":"//game.gtimg.cn/images/lol/companion/Ranked_Furyhorn_PO.png"},
    {"name":"德玛西亚 银翼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Cream_Tier1.Companions.png"},
    {"name":"德玛西亚 银翼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Cream_Tier2.Companions.png"},
    {"name":"德玛西亚 银翼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Cream_Tier3.Companions.png"},
    {"name":"雪樱 银翼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Hawk_Tier1.Companions.png"},
    {"name":"雪樱 银翼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Hawk_Tier2.Companions.png"},
    {"name":"雪樱 银翼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Hawk_Tier3.Companions.png"},
    {"name":"晨辉 银翼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Yellow_Tier1.Companions.png"},
    {"name":"晨辉 银翼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Yellow_Tier2.Companions.png"},
    {"name":"晨辉 银翼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Yellow_Tier3.Companions.png"},
    {"name":"玫瑰花 银翼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Pink_Tier1.Companions.png"},
    {"name":"玫瑰花 银翼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Pink_Tier2.Companions.png"},
    {"name":"玫瑰花 银翼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Pink_Tier3.Companions.png"},
    {"name":"热带 银翼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Parrot_Tier1.Companions.png"},
    {"name":"热带 银翼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Parrot_Tier2.Companions.png"},
    {"name":"热带 银翼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Parrot_Tier3.Companions.png"},
    {"name":"失落 银翼1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Dark_Tier1.Companions.png"},
    {"name":"失落 银翼2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Dark_Tier2.Companions.png"},
    {"name":"失落 银翼3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Griffin_Dark_Tier3.Companions.png"},
    // {"name":"星之守护者 银翼 1星","src":"//game.gtimg.cn/images/lol/companion/SG_Silverwing_Tier1.png"},
    // {"name":"星之守护者 银翼 2星","src":"//game.gtimg.cn/images/lol/companion/SG_Silverwing_Tier2.png"},
    // {"name":"星之守护者 银翼 3星","src":"//game.gtimg.cn/images/lol/companion/SG_Silverwing_Tier3.png"},
    // {"name":"胜利银翼","src":"//game.gtimg.cn/images/lol/companion/Ranked_Silverwing_PO.png"},
    {"name":"暗影岛 幽灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Spooky_Tier1.Companions.png"},
    {"name":"暗影岛 幽灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Spooky_Tier2.Companions.png"},
    {"name":"暗影岛 幽灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Spooky_Tier3.Companions.png"},
    {"name":"火焰血脉 幽灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Fire_Tier1.Companions.png"},
    {"name":"火焰血脉 幽灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Fire_Tier2.Companions.png"},
    {"name":"火焰血脉 幽灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Fire_Tier3.Companions.png"},
    {"name":"月爪 幽灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Blue_Tier1.Companions.png"},
    {"name":"月爪 幽灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Blue_Tier2.Companions.png"},
    {"name":"月爪 幽灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Blue_Tier3.Companions.png"},
    {"name":"剧毒 幽灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Green_Tier1.Companions.png"},
    {"name":"剧毒 幽灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Green_Tier2.Companions.png"},
    {"name":"剧毒 幽灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Green_Tier3.Companions.png"},
    {"name":"黑暗物质 幽灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Purple_Tier1.Companions.png"},
    {"name":"黑暗物质 幽灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Purple_Tier2.Companions.png"},
    {"name":"黑暗物质 幽灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Purple_Tier3.Companions.png"},
    {"name":"暗影面具 幽灵1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Black_Tier1.Companions.png"},
    {"name":"暗影面具 幽灵2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Black_Tier2.Companions.png"},
    {"name":"暗影面具 幽灵3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Ghosty_Black_Tier3.Companions.png"},
    {"name":"K/DA POP/STARS 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_KDAAhri_KDA2_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_KDAAhri_KDA2_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 静尾 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_KDAAhri_KDA1_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 静尾 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_KDAAhri_KDA1_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_KDAAhri_KDA1_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 静尾 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_SpiritFox_KDAAhri_KDA2_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 宇宙鱿 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_DSSquid_KDAEvelynn_KDA1_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 宇宙鱿 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_DSSquid_KDAEvelynn_KDA1_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 宇宙鱿 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_DSSquid_KDAEvelynn_KDA2_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 宇宙鱿 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_DSSquid_KDAEvelynn_KDA2_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 宇宙鱿 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_DSSquid_KDAEvelynn_KDA2_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 小马 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Pegasus_KDASeraphine_KDA1_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 羽饰骑士 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_KDAAkali_KDA2_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 羽饰骑士 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_KDAAkali_KDA2_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 羽饰骑士 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_KDAAkali_KDA1_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 羽饰骑士 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_KDAAkali_KDA1_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 羽饰骑士 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_KDAAkali_KDA2_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 羽饰骑士 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_PenguKnight_KDAAkali_KDA1_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 小马 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Pegasus_KDASeraphine_KDA2_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 小马 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Pegasus_KDASeraphine_KDA1_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 小马 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Pegasus_KDASeraphine_KDA1_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 小马 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Pegasus_KDASeraphine_KDA2_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 小马 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Pegasus_KDASeraphine_KDA2_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 宇宙鱿 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_DSSquid_KDAEvelynn_KDA1_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 怒角 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_KDAKaiSa_KDA2_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 怒角 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_KDAKaiSa_KDA2_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 怒角 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_KDAKaiSa_KDA1_Tier1.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 怒角 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_KDAKaiSa_KDA1_Tier2.LittleLegends_10_23.png"},
    {"name":"K/DA ALL OUT 怒角 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_KDAKaiSa_KDA1_Tier3.LittleLegends_10_23.png"},
    {"name":"K/DA POP/STARS 怒角 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_GrumpyLion_KDAKaiSa_KDA2_Tier1.LittleLegends_10_23.png"},
    {"name":"胖胖龙 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Classic_Tier1.LittleLegends_10_19.png"},
    {"name":"胖胖龙 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Classic_Tier2.LittleLegends_10_19.png"},
    {"name":"胖胖龙 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Classic_Tier3.LittleLegends_10_19.png"},
    {"name":"胖水龙 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Atlantean_Tier1.LittleLegends_10_19.png"},
    {"name":"胖水龙 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Atlantean_Tier2.LittleLegends_10_19.png"},
    {"name":"胖水龙 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Atlantean_Tier3.LittleLegends_10_19.png"},
    {"name":"胖石龙 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_EarthTitan_Tier1.LittleLegends_10_19.png"},
    {"name":"胖石龙 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_EarthTitan_Tier2.LittleLegends_10_19.png"},
    {"name":"胖石龙 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_EarthTitan_Tier3.LittleLegends_10_19.png"},
    {"name":"胖火龙 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Fireborn_Tier1.LittleLegends_10_19.png"},
    {"name":"胖火龙 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Fireborn_Tier2.LittleLegends_10_19.png"},
    {"name":"胖火龙 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Fireborn_Tier3.LittleLegends_10_19.png"},
    {"name":"胖达龙 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_PreciousPanda_Tier1.LittleLegends_10_19.png"},
    {"name":"胖达龙 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_PreciousPanda_Tier2.LittleLegends_10_19.png"},
    {"name":"胖达龙 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_PreciousPanda_Tier3.LittleLegends_10_19.png"},
    {"name":"胖嗡嗡龙 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Honeybuzz_Tier1.LittleLegends_10_19.png"},
    {"name":"胖嗡嗡龙 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Honeybuzz_Tier2.LittleLegends_10_19.png"},
    {"name":"胖嗡嗡龙 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Choncc_Honeybuzz_Tier3.LittleLegends_10_19.png"},
    {"name":"夜煞 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Classic_Tier1.LittleLegends_10_19.png"},
    {"name":"夜煞 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Classic_Tier2.LittleLegends_10_19.png"},
    {"name":"夜煞 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Classic_Tier3.LittleLegends_10_19.png"},
    {"name":"黑雾 夜煞 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_BlackMist_Tier1.LittleLegends_10_19.png"},
    {"name":"黑雾 夜煞 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_BlackMist_Tier2.LittleLegends_10_19.png"},
    {"name":"黑雾 夜煞 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_BlackMist_Tier3.LittleLegends_10_19.png"},
    {"name":"果味软糖 夜煞 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_FruityTooty_Tier1.LittleLegends_10_19.png"},
    {"name":"果味软糖 夜煞 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_FruityTooty_Tier2.LittleLegends_10_19.png"},
    {"name":"果味软糖 夜煞 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_FruityTooty_Tier3.LittleLegends_10_19.png"},
    {"name":"雷霆狂龙 夜煞 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Thunderbeast_Tier1.LittleLegends_10_19.png"},
    {"name":"雷霆狂龙 夜煞 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Thunderbeast_Tier2.LittleLegends_10_19.png"},
    {"name":"雷霆狂龙 夜煞 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Thunderbeast_Tier3.LittleLegends_10_19.png"},
    {"name":"腥红之月 夜煞 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_BloodMoon_Tier1.LittleLegends_10_19.png"},
    {"name":"腥红之月 夜煞 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_BloodMoon_Tier2.LittleLegends_10_19.png"},
    {"name":"腥红之月 夜煞 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_BloodMoon_Tier3.LittleLegends_10_19.png"},
    {"name":"海克斯黄金 夜煞 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Hexgold_Tier1.LittleLegends_10_19.png"},
    {"name":"海克斯黄金 夜煞 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Hexgold_Tier2.LittleLegends_10_19.png"},
    {"name":"海克斯黄金 夜煞 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_Umbra_Hexgold_Tier3.LittleLegends_10_19.png"},
    {"name":"敖兴 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Classic_Tier1.LittleLegends_10_19.png"},
    {"name":"敖兴 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Classic_Tier2.LittleLegends_10_19.png"},
    {"name":"敖兴 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Classic_Tier3.LittleLegends_10_19.png"},
    {"name":"远古巨龙 敖兴 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Elder_Tier1.LittleLegends_10_19.png"},
    {"name":"远古巨龙 敖兴 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Elder_Tier2.LittleLegends_10_19.png"},
    {"name":"远古巨龙 敖兴 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Elder_Tier3.LittleLegends_10_19.png"},
    {"name":"神龙烈焰 敖兴 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Firecracker_Tier1.LittleLegends_10_19.png"},
    {"name":"神龙烈焰 敖兴 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Firecracker_Tier2.LittleLegends_10_19.png"},
    {"name":"神龙烈焰 敖兴 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Firecracker_Tier3.LittleLegends_10_19.png"},
    {"name":"暗星 敖兴 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_DarkStar_Tier1.LittleLegends_10_19.png"},
    {"name":"暗星 敖兴 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_DarkStar_Tier2.LittleLegends_10_19.png"},
    {"name":"暗星 敖兴 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_DarkStar_Tier3.LittleLegends_10_19.png"},
    {"name":"神龙 敖兴 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Divine_Tier1.LittleLegends_10_19.png"},
    {"name":"神龙 敖兴 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Divine_Tier2.LittleLegends_10_19.png"},
    {"name":"神龙 敖兴 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_Divine_Tier3.LittleLegends_10_19.png"},
    {"name":"铸星龙王 敖兴 1星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_StarForger_Tier1.LittleLegends_10_19.png"},
    {"name":"铸星龙王 敖兴 2星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_StarForger_Tier2.LittleLegends_10_19.png"},
    {"name":"铸星龙王 敖兴 3星","src":"//game.gtimg.cn/images/lol/companion/Loot_AoShin_StarForger_Tier3.LittleLegends_10_19.png"},
    
];


// 皮肤加英雄
var dataAttr7=[
    {"num":"1","name1":"安妮","id":"1011","name":"银河魔装机神 安妮"},
    {"num":"2","name1":"奥拉夫","id":"2005","name":"黑暗骑士 奥拉夫"},
    {"num":"3","name1":"加里奥","id":"3005","name":"风执事 加里奥"},
    {"num":"4","name1":"崔斯特","id":"4005","name":"西部牛仔 崔斯特"},
    {"num":"5","name1":"赵信","id":"5013","name":"屠龙勇士 赵信"},
    {"num":"7","name1":"乐芙兰","id":"7004","name":"邪鸦魅影 乐芙兰"},
    {"num":"8","name1":"弗拉基米尔","id":"8008","name":"黑潮 弗拉基米尔"},
    {"num":"12","name1":"阿利斯塔","id":"12008","name":"黑暗骑士 阿利斯塔"},
    {"num":"14","name1":"赛恩","id":"14004","name":"战争机器 赛恩"},
    {"num":"15","name1":"希维尔","id":"15007","name":"光明骑士 希维尔"},
    {"num":"16","name1":"索拉卡","id":"16006","name":"源代码 索拉卡"},
    {"num":"17","name1":"提莫","id":"17004","name":"提莫:'约德尔人的一大步'"},
    {"num":"21","name1":"厄运小姐","id":"21008","name":"女帝 厄运小姐"},
    {"num":"22","name1":"艾希","id":"22007","name":"黑暗骑士 艾希"},
    {"num":"23","name1":"泰达米尔","id":"23007","name":"梦魇 泰达米尔"},
    {"num":"24","name1":"贾克斯","id":"24012","name":"光明骑士 贾克斯"},
    {"num":"28","name1":"伊芙琳","id":"28004","name":"惊天魔盗 伊芙琳"},
    {"num":"29","name1":"图奇","id":"29006","name":"绝影神偷 图奇"},
    {"num":"31","name1":"科加斯","id":"31005","name":"战地巨兽 科加斯"},
    {"num":"39","name1":"艾瑞莉娅","id":"39004","name":"冰霜之刃 艾瑞莉娅"},
    {"num":"51","name1":"凯特琳","id":"51006","name":"铁血狙击手 凯特琳"},
    {"num":"54","name1":"墨菲特","id":"54006","name":"霸天巨兽 墨菲特"},
    {"num":"55","name1":"卡特琳娜","id":"55004","name":"暗夜猫女 卡特琳娜"},
    {"num":"58","name1":"雷克顿","id":"58005","name":"枯萎之壤 雷克顿"},
    {"num":"61","name1":"奥莉安娜","id":"61007","name":"死兆星 奥莉安娜"},
    {"num":"63","name1":"布兰德","id":"63005","name":"灵魂烈焰 布兰德"},
    {"num":"64","name1":"李青","id":"64010","name":"地下拳王 李青"},
    {"num":"67","name1":"薇恩","id":"67006","name":"苍穹之光 薇恩"},
    {"num":"68","name1":"兰博","id":"68003","name":"银河魔装机神 兰博"},
    {"num":"79","name1":"古拉加斯","id":"79009","name":"古拉加斯·碎桶者"},
    {"num":"80","name1":"潘森","id":"80008","name":"面包之王 潘森"},
    {"num":"81","name1":"伊泽瑞尔","id":"81008","name":"黑桃皇牌 伊泽瑞尔"},
    {"num":"86","name1":"盖伦","id":"86004","name":"死亡骑士 盖伦"},
    {"num":"92","name1":"锐雯","id":"92003","name":"兔女郎 锐雯"},
    {"num":"99","name1":"拉克丝","id":"99006","name":"星之守护者 拉克丝"},
    {"num":"103","name1":"阿狸","id":"103004","name":"偶像歌手 阿狸"},
    {"num":"104","name1":"格雷福斯","id":"104003","name":"黑帮教父 格雷福斯"},
    {"num":"105","name1":"菲兹","id":"105009","name":"银河魔装机神 菲兹"},
    {"num":"107","name1":"雷恩加尔","id":"107002","name":"暗黑武士 雷恩加尔"},
    {"num":"110","name1":"韦鲁斯","id":"110006","name":"死兆星 韦鲁斯"},
    {"num":"114","name1":"菲奥娜","id":"114003","name":"女校长 菲奥娜"},
    {"num":"117","name1":"璐璐","id":"117003","name":"驯龙女巫 璐璐"},
    {"num":"119","name1":"德莱文","id":"119003","name":"金牌主播 德莱文"},
    {"num":"121","name1":"卡兹克","id":"121003","name":"死亡绽放 卡兹克"},
    {"num":"122","name1":"德莱厄斯","id":"122008","name":"热血班长 德莱厄斯"},
    {"num":"131","name1":"黛安娜","id":"131003","name":"无限烈焰 黛安娜"},
    {"num":"134","name1":"辛德拉","id":"134002","name":"亚特兰蒂斯 辛德拉"},
    {"num":"145","name1":"卡莎","id":"145001","name":"弹幕天使 卡莎"},
    {"num":"157","name1":"亚索","id":"157001","name":"西部牛仔 亚索"},
    {"num":"164","name1":"卡蜜尔","id":"164001","name":"源代码 卡蜜尔"},
    {"num":"222","name1":"金克丝","id":"222003","name":"丧尸杀手 金克丝"},
    {"num":"236","name1":"卢锡安","id":"236001","name":"职业杀手 卢锡安"},
    {"num":"238","name1":"劫","id":"238001","name":"冲击之刃 劫"},
    {"num":"245","name1":"艾克","id":"245002","name":"任性学霸 艾克"},
    {"num":"254","name1":"蔚","id":"254002","name":"女警官 蔚"},
    {"num":"266","name1":"亚托克斯","id":"266007","name":"腥红之月 亚托克斯"},
    {"num":"412","name1":"锤石","id":"412005","name":"死兆星 锤石"},
    {"num":"497","name1":"洛","id":"497001","name":"晨星之翎 洛"},
    {"num":"498","name1":"霞","id":"498001","name":"暮星之羽 霞"},
    {"num":"59","name1":" 嘉文四世","id":"59007","name":"暗星 嘉文四世"},
    {"num":"34","name1":"艾尼维亚","id":"34008","name":"千纸凤凰 艾尼维亚"},
    
];


var skins = [dataAttr1,dataAttr2,dataAttr3,dataAttr4,dataAttr5,dataAttr6,dataAttr7];/* #t6Hl8#E44869A24C326C89D8DF4E2B3F886F9B */